# Simple Multilayer Perceptron(ANN)

### Importing the libraries

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values  #col taken from credit score
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
#encoding dependent variable template 
# gender should be either 1 or 0 i.e., male or female
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])  # 2 from X

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
#encoding independent variable template
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') #1-->geography
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential() 
#initialzed as a sequence of layers 
#sequential class to do the above

### Adding the input layer and the first hidden layer

In [ ]:
#dense class is used
#add method is from sequential class
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#relu ---> rectifier activation function
#units ---> no. of neurons in the hidden layers

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#output we get is 0 or 1, i.e. binary so units = 1
#sigmoid activation func gives the value and probability values (0-1)

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#for binary values --- 'binary_crossentropy'
#for non binary values ---- 'categorical_crossentropy'
#adam is a stochastic gradient descent method
#Accuracy calculates the percentage of predicted values (yPred) that match with actual values (yTrue).

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5721 - accuracy: 0.7614
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4705 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4410 - accuracy: 0.7976
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4323 - accuracy: 0.8033
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4285 - accuracy: 0.8056
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4255 - accuracy: 0.8071
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4221 - accuracy: 0.8099
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accuracy: 0.8121
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4126 - accuracy: 0.8158
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4070 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) #convert predicted prob to 0 or 1 i.e., binary
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 195  210]]


0.8595